
FROM node:22.19.0-alpine

WORKDIR /app

# mark runtime as test (doesn't affect build-time install of dev deps)
ENV NODE_ENV=test

# Install dependencies as root
COPY package*.json ./
RUN npm ci

# Copy source code
COPY src ./src
COPY tests ./tests
COPY eslint.config.mjs ./

# Fix ownership and run as the standard `node` user
RUN chown -R node:node /app
USER node

CMD ["npm", "run", "test"]
