
FROM node:22.19.0-alpine

WORKDIR /app

# Install dependencies as root
COPY package*.json ./
RUN npm ci

# Copy source code
COPY src ./src
COPY tests ./tests
COPY eslint.config.mjs ./

# Fix ownership and change user
RUN chown -R 65532:65532 /app
USER 65532

CMD ["npm", "run", "test"]
