name: node.js CI

on:
    push:
        branches: [master, sho-gha]
    pull_request:
        branches: [master]

jobs:
    Checkout-and-Build-Docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
            - name: Build Docker containers
              run: docker compose up --abort-on-container-exit --build

    Test-and-lint-Docker:
        runs-on: ubuntu-latest
        needs: Checkout-and-Build-Docker
        steps:
            - name: Run Docker tests
              run: docker compose run test
            - name: Run Docker lint
              run: docker compose run lint
    report:
        runs-on: ubuntu-latest
        needs: Test-and-lint-Docker
        steps:
            - name: Report job status
              uses: dorny/test-reporter@v2
              with:
                artifact: test-results
                path: "*.xml"
                reporter: mocha-json
